### ISSUE TITLE
this install dont works

### ISSUE THREAD

**Issue by bibi-blocksberg** [Magic-Bots/xenon#121]
With Docker (Recommended)
Download and install docker on your operating system.

Build and run it with docker-compose:

Download / Clone the repository (preferably the selfhost branch)
Edit the xenon.env file and change the token
You might wanna change some values in xenon/config.py e.g. the prefix (maybe disable the templates cog aswell)
Create a xenon/logs directory for the log files
Run docker-compose build
Run docker-compose up
The database and the bot should start up.

      
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/logging/handlers.py", line 71, in emit

    logging.FileHandler.emit(self, record)

  File "/usr/local/lib/python3.7/logging/__init__.py", line 1126, in emit

    self.stream = self._open()

  File "/usr/local/lib/python3.7/logging/__init__.py", line 1116, in _open

    return open(self.baseFilename, self.mode, encoding=self.encoding)

NameError: name 'open' is not defined

Call stack:

  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 305, in __del__

    self._loop.call_exception_handler(context)

  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1641, in call_exception_handler

    self.default_exception_handler(context)

  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1615, in default_exception_handler

    logger.error('\n'.join(log_lines), exc_info=exc_info)

Message: 'Unclosed client session\nclient_session: <aiohttp.client.ClientSession object at 0x7f5fc687f990>'

Arguments: ()

2020-01-10 14:36:05,570 [WARNING] PyNaCl is not installed, voice will NOT be supported

2020-01-10 14:36:05,584 [INFO] Running shards: 

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 607, in _load_from_module_spec

    setup(self)

  File "/usr/src/app/cogs/templates.py", line 470, in setup

    bot.add_cog(Templates(bot))

  File "/usr/src/app/cogs/templates.py", line 20, in __init__

    adapter=AsyncWebhookAdapter(self.bot.session))

  File "/usr/local/lib/python3.7/site-packages/discord/webhook.py", line 499, in from_url

    raise InvalidArgument('Invalid webhook URL given.')

discord.errors.InvalidArgument: Invalid webhook URL given.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/usr/local/lib/python3.7/cProfile.py", line 185, in <module>

    main()

  File "/usr/local/lib/python3.7/cProfile.py", line 178, in main

    runctx(code, globs, None, options.outfile, options.sort)

  File "/usr/local/lib/python3.7/cProfile.py", line 20, in runctx

    filename, sort)

  File "/usr/local/lib/python3.7/profile.py", line 62, in runctx

    prof.runctx(statement, globals, locals)

  File "/usr/local/lib/python3.7/cProfile.py", line 100, in runctx

    exec(cmd, globals, locals)

  File "launcher.py", line 19, in <module>

    run_bot()

  File "launcher.py", line 14, in run_bot

    bot = loop.run_until_complete(prepare_bot(loop))

  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete

    return future.result()

  File "launcher.py", line 9, in prepare_bot

    return Xenon(loop=loop)

  File "/usr/src/app/bot.py", line 52, in __init__

    self.load_extension("cogs." + ext)

  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 652, in load_extension

    self._load_from_module_spec(spec, name)

  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 612, in _load_from_module_spec

    raise errors.ExtensionFailed(key, e) from e

discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.templates' raised an error: InvalidArgument: Invalid webhook URL given.

2020-01-10 14:36:07,273 [ERROR] Task was destroyed but it is pending!

task: <Task pending coro=<Loop._loop() running at /usr/local/lib/python3.7/site-packages/discord/ext/tasks/__init__.py:82> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f83dc39f950>()]>>

2020-01-10 14:36:07,287 [ERROR] Unclosed client session

client_session: <aiohttp.client.ClientSession object at 0x7f83dcc6a950>

--- Logging error ---

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/logging/handlers.py", line 71, in emit

    logging.FileHandler.emit(self, record)

  File "/usr/local/lib/python3.7/logging/__init__.py", line 1126, in emit

    self.stream = self._open()

  File "/usr/local/lib/python3.7/logging/__init__.py", line 1116, in _open

    return open(self.baseFilename, self.mode, encoding=self.encoding)

NameError: name 'open' is not defined

Call stack:

  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1641, in call_exception_handler

    self.default_exception_handler(context)

  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1615, in default_exception_handler

    logger.error('\n'.join(log_lines), exc_info=exc_info)

Message: 'Task was destroyed but it is pending!\ntask: <Task pending coro=<Loop._loop() running at /usr/local/lib/python3.7/site-packages/discord/ext/tasks/__init__.py:82> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f83dc39f950>()]>>'

Arguments: ()

--- Logging error ---

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/logging/handlers.py", line 71, in emit

    logging.FileHandler.emit(self, record)

  File "/usr/local/lib/python3.7/logging/__init__.py", line 1126, in emit

    self.stream = self._open()

  File "/usr/local/lib/python3.7/logging/__init__.py", line 1116, in _open

    return open(self.baseFilename, self.mode, encoding=self.encoding)

NameError: name 'open' is not defined

Call stack:

  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 305, in __del__

    self._loop.call_exception_handler(context)

  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1641, in call_exception_handler

    self.default_exception_handler(context)

  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1615, in default_exception_handler

    logger.error('\n'.join(log_lines), exc_info=exc_info)

Message: 'Unclosed client session\nclient_session: <aiohttp.client.ClientSession object at 0x7f83dcc6a950>'

Arguments: ()

**Comment by ThatLifeofGames** [comment]
Please join the support server for support with selfhosting, this is for suggestions and bugs not support.
