### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xiecie** [Magic-Bots/xenon#84]
help me please 
```
xenon_1    | Traceback (most recent call last):
xenon_1    |   File "launcher.py", line 12, in <module>
xenon_1    |     bot = loop.run_until_complete(prepare_bot(loop))
xenon_1    |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
xenon_1    |     return future.result()
xenon_1    |   File "launcher.py", line 7, in prepare_bot
xenon_1    |     return Xenon(loop=_loop)
xenon_1    |   File "/usr/src/app/bot.py", line 23, in __init__
xenon_1    |     *args, **kwargs)
xenon_1    |   File "/usr/src/app/bot.py", line 91, in config
xenon_1    |     return __import__("config")
xenon_1    |   File "/usr/src/app/config.py", line 12, in <module>
xenon_1    |     pod_id = int(_hostname.split("-")[-1]) if _hostname is not None else 0
xenon_1    | ValueError: invalid literal for int() with base 10: '70843896f72e'
`[](url)`
```

**Comment by merlinfuchs** [comment]
Looks like your are running a pretty old version, please update.
